// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const swaggerJSON = `{
  "swagger": "2.0",
  "info": {
    "title": "Segmentation API",
    "description": "API de segmentações com worker de processamento de arquivos",
    "version": "1.0.0",
    "contact": {
      "name": "Charlen Rodrigues"
    }
  },
  "host": "localhost:8080",
  "basePath": "/",
  "schemes": [
    "http",
    "https"
  ],
  "paths": {
    "/health": {
      "get": {
        "summary": "Health Check",
        "description": "Check if the API is running and healthy",
        "operationId": "health",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "status": {
                  "type": "string",
                  "example": "healthy"
                }
              }
            }
          }
        }
      }
    },
    "/users/{user_id}/segmentations": {
      "get": {
        "summary": "Get User Segmentations",
        "description": "Retrieve all segmentations for a specific user",
        "operationId": "getUserSegmentations",
        "parameters": [
          {
            "name": "user_id",
            "in": "path",
            "description": "User ID",
            "required": true,
            "type": "integer",
            "format": "int64"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "user_id": {
                  "type": "integer",
                  "format": "int64"
                },
                "segmentations": {
                  "type": "object",
                  "properties": {
                    "specialties": {
                      "type": "array",
                      "items": {
                        "$ref": "#/definitions/Segmentation"
                      }
                    },
                    "drugs": {
                      "type": "array",
                      "items": {
                        "$ref": "#/definitions/Segmentation"
                      }
                    },
                    "patients": {
                      "type": "array",
                      "items": {
                        "$ref": "#/definitions/Segmentation"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid user ID"
          },
          "404": {
            "description": "User not found"
          },
          "500": {
            "description": "Internal server error"
          }
        }
      }
    }
  },
  "definitions": {
    "Segmentation": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "description": "Segmentation name"
        },
        "data": {
          "type": "object",
          "description": "Additional segmentation data"
        }
      }
    }
  }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}{
	Version:     "1.0.0",
	Host:        "localhost:8080",
	BasePath:    "/",
	Schemes:     []string{"http", "https"},
	Title:       "Segmentation API",
	Description: "API de segmentações com worker de processamento de arquivos",
}

func init() {
	swag.Register("swagger", &swag.Spec{
		Version:          SwaggerInfo.Version,
		Host:             SwaggerInfo.Host,
		BasePath:         SwaggerInfo.BasePath,
		Schemes:          SwaggerInfo.Schemes,
		Title:            SwaggerInfo.Title,
		Description:      SwaggerInfo.Description,
		InfoInstanceName: "swagger",
		SwaggerTemplate:  swaggerJSON,
	})
}
